apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world-app
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 80  # Container port
  type: LoadBalancer  # Use LoadBalancer for external access
